// <auto-generated />
namespace ShopCart.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class creating_Invoice_table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(creating_Invoice_table));
        
        string IMigrationMetadata.Id
        {
            get { return "202007011915300_creating_Invoice_table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
